### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/Earvel#1]
# Todo
- [ ] Setup

- [ ] Registration system

- [ ] Login and Logout system

- [ ] Password reset system

- [ ] Password change system
