### ISSUE TITLE
Follow System

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/Earvel#13]
# Todo
- [x] Add Contact Model to Accounts app

- [ ] CreateView(follow) and DeleteView(unfollow)

- [ ] Implement to templates
