### ISSUE TITLE
Tagging system

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/Earvel#22]
# Todo

- [x] Install django-taggit

- [x] Edit form and model

- [x] Add similar_posts system
