### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/Earvel#3]
# Todo

- [x] Startapp Page 

- [x] Setup templates and Static

- [x] Install Django-bulma

- [x] home.html, _base.html
