### ISSUE TITLE
Setup Docker and Postgresql

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/Earvel#4]
# Todo

- [x] Set up Dockerfile and docker-compose.yml

- [x] Set up database in setting.spy

- [x] Change language to Japanese in settings.py
